##############################################################################
# Variables
##############################################################################
TARGET=lfs_core
LIBNAME=lfs_core

SRC=lfs.ml

DEP_LIBS=commons commons_ocollection commons_core

INCLUDES=${DEP_LIBS:%=-I ../external/%}
#LIBS=${DEP_LIBS:%=../external/%/lib.cma}

EXPORTSRC=lfs.mli

include ../Makefile.common
